//! Autogenerated weights for daos_agency
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-10-29, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("local"), DB CACHE: 1024

// Executed Command:
    // target/release/tico
    // benchmark
    // pallet
    // --execution=wasm
    // --chain
    // local
    // --wasm-execution=compiled
    // --pallet=daos_agency
    // --extrinsic=*
    // --steps=50
    // --repeat=20
    // --template=./.maintain/daos-weight-template.hbs
    // --output
    // ./pallets/daos/agency/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for daos_agency.
pub trait WeightInfo {
    fn execute() -> Weight;
    fn propose() -> Weight;
    fn vote() -> Weight;
    fn close() -> Weight;
    fn disapprove_proposal() -> Weight;
    fn set_motion_duration() -> Weight;
    fn set_max_proposals() -> Weight;
    fn set_max_members() -> Weight;
    fn set_ensure_origin_for_every_call() -> Weight;
}

/// Weights for daos_agency using the Substrate node and recommended hardware.
pub struct DaosWeight<T>(PhantomData<T>);
        impl<T: frame_system::Config> WeightInfo for DaosWeight<T> {
            // Storage: DaoAgency CollectiveMembers (r:1 w:0)
        fn execute() -> Weight {
            Weight::from_ref_time(20_0000_0000)
        }
            // Storage: DaoAgency CollectiveMembers (r:1 w:0)
            // Storage: DaoAgency ProposalOf (r:1 w:1)
            // Storage: DaoAgency Proposals (r:1 w:1)
            // Storage: DaoAgency MaxProposals (r:1 w:0)
            // Storage: DaoAgency ProposalCount (r:1 w:1)
            // Storage: DaoAgency MotionDuration (r:1 w:0)
            // Storage: DaoAgency Voting (r:0 w:1)
        fn propose() -> Weight {
                Weight::from_ref_time(20_0000_0000)
        }
            // Storage: DaoAgency CollectiveMembers (r:1 w:0)
            // Storage: DaoAgency Voting (r:1 w:1)
        fn vote() -> Weight {
                Weight::from_ref_time(20_0000_0000)
        }
            // Storage: DaoAgency Voting (r:1 w:1)
            // Storage: DaoAgency CollectiveMembers (r:1 w:0)
            // Storage: DaoAgency ProposalOf (r:1 w:1)
            // Storage: DaoAgency Proposals (r:1 w:1)
        fn close() -> Weight {
                Weight::from_ref_time(20_0000_0000)
        }
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoAgency Proposals (r:1 w:1)
            // Storage: DaoAgency Voting (r:0 w:1)
            // Storage: DaoAgency ProposalOf (r:0 w:1)
        fn disapprove_proposal() -> Weight {
                Weight::from_ref_time(20_0000_0000)
        }
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoAgency MotionDuration (r:0 w:1)
        fn set_motion_duration() -> Weight {
                Weight::from_ref_time(20_0000_0000)
        }
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoAgency MaxProposals (r:0 w:1)
        fn set_max_proposals() -> Weight {
                Weight::from_ref_time(20_0000_0000)
        }
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoAgency MaxMembers (r:0 w:1)
        fn set_max_members() -> Weight {
                Weight::from_ref_time(20_0000_0000)
        }
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoAgency EnsureOrigins (r:0 w:1)
        fn set_ensure_origin_for_every_call() -> Weight {
                Weight::from_ref_time(20_0000_0000)
        }
    }

    // For backwards compatibility and tests
    impl WeightInfo for () {
            // Storage: DaoAgency CollectiveMembers (r:1 w:0)
        fn execute() -> Weight {
                Weight::from_ref_time(20_0000_0000)
        }
            // Storage: DaoAgency CollectiveMembers (r:1 w:0)
            // Storage: DaoAgency ProposalOf (r:1 w:1)
            // Storage: DaoAgency Proposals (r:1 w:1)
            // Storage: DaoAgency MaxProposals (r:1 w:0)
            // Storage: DaoAgency ProposalCount (r:1 w:1)
            // Storage: DaoAgency MotionDuration (r:1 w:0)
            // Storage: DaoAgency Voting (r:0 w:1)
        fn propose() -> Weight {
                Weight::from_ref_time(20_0000_0000)
        }
            // Storage: DaoAgency CollectiveMembers (r:1 w:0)
            // Storage: DaoAgency Voting (r:1 w:1)
        fn vote() -> Weight {
                Weight::from_ref_time(20_0000_0000)
        }
            // Storage: DaoAgency Voting (r:1 w:1)
            // Storage: DaoAgency CollectiveMembers (r:1 w:0)
            // Storage: DaoAgency ProposalOf (r:1 w:1)
            // Storage: DaoAgency Proposals (r:1 w:1)
        fn close() -> Weight {
                Weight::from_ref_time(20_0000_0000)
        }
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoAgency Proposals (r:1 w:1)
            // Storage: DaoAgency Voting (r:0 w:1)
            // Storage: DaoAgency ProposalOf (r:0 w:1)
        fn disapprove_proposal() -> Weight {
                Weight::from_ref_time(20_0000_0000)
        }
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoAgency MotionDuration (r:0 w:1)
        fn set_motion_duration() -> Weight {
                Weight::from_ref_time(20_0000_0000)
        }
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoAgency MaxProposals (r:0 w:1)
        fn set_max_proposals() -> Weight {
                Weight::from_ref_time(20_0000_0000)
        }
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoAgency MaxMembers (r:0 w:1)
        fn set_max_members() -> Weight {
                Weight::from_ref_time(20_0000_0000)
        }
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoAgency EnsureOrigins (r:0 w:1)
        fn set_ensure_origin_for_every_call() -> Weight {
                Weight::from_ref_time(20_0000_0000)
        }
    }