//! Autogenerated weights for daos_square
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-11-27, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("local"), DB CACHE: 1024

// Executed Command:
    // target/release/tico
    // benchmark
    // pallet
    // --execution=wasm
    // --chain
    // local
    // --wasm-execution=compiled
    // --pallet=daos_square
    // --extrinsic=*
    // --steps=50
    // --repeat=20
    // --template=./.maintain/daos-weight-template.hbs
    // --output
    // ./pallets/daos/square/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for daos_square.
pub trait WeightInfo {
    fn propose() -> Weight;
    fn second() -> Weight;
    fn open_table() -> Weight;
    fn vote_for_referendum() -> Weight;
    fn cancel_vote() -> Weight;
    fn enact_proposal() -> Weight;
    fn unlock() -> Weight;
    fn set_min_vote_weight_for_every_call() -> Weight;
    fn set_max_public_props() -> Weight;
    fn set_launch_period() -> Weight;
    fn set_minimum_deposit() -> Weight;
    fn set_voting_period() -> Weight;
    fn set_rerserve_period() -> Weight;
    fn set_enactment_period() -> Weight;
}

/// Weights for daos_square using the Substrate node and recommended hardware.
pub struct DaosWeight<T>(PhantomData<T>);
        impl<T: frame_system::Config> WeightInfo for DaosWeight<T> {
            // Storage: System Account (r:1 w:1)
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoSquare MinimumDeposit (r:1 w:0)
            // Storage: DaoSquare PublicPropCount (r:1 w:1)
            // Storage: DaoSquare PublicProps (r:1 w:1)
            // Storage: DaoSquare MaxPublicProps (r:1 w:0)
            // Storage: DaoSquare DepositOf (r:0 w:1)
        fn propose() -> Weight {
        (76_544_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(6 as Weight))
            .saturating_add(T::DbWeight::get().writes(4 as Weight))
        }
            // Storage: DaoSquare DepositOf (r:1 w:1)
            // Storage: System Account (r:1 w:1)
            // Storage: DaoSquare ReservePeriod (r:1 w:0)
            // Storage: DaoSquare ReserveOf (r:1 w:1)
        fn second() -> Weight {
        (54_657_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().writes(3 as Weight))
        }
            // Storage: DaoSquare LaunchTag (r:1 w:0)
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoSquare LaunchPeriod (r:1 w:0)
            // Storage: DaoSquare PublicProps (r:1 w:1)
            // Storage: DaoSquare DepositOf (r:1 w:1)
            // Storage: DaoSquare VotingPeriod (r:1 w:0)
            // Storage: DaoSquare EnactmentPeriod (r:1 w:0)
            // Storage: DaoSquare ReferendumCount (r:1 w:1)
            // Storage: DaoSquare ReferendumInfoOf (r:0 w:1)
        fn open_table() -> Weight {
        (60_214_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(8 as Weight))
            .saturating_add(T::DbWeight::get().writes(4 as Weight))
        }
            // Storage: DaoSquare ReferendumInfoOf (r:1 w:1)
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoSquare VotesOf (r:1 w:1)
        fn vote_for_referendum() -> Weight {
        (42_628_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(3 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
        }
            // Storage: DaoSquare ReferendumInfoOf (r:1 w:1)
            // Storage: DaoSquare VotesOf (r:1 w:1)
        fn cancel_vote() -> Weight {
        (40_795_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
        }
            // Storage: DaoSquare ReferendumInfoOf (r:1 w:1)
            // Storage: DaoSquare MinVoteWeightOf (r:1 w:0)
            // Storage: CreateDao Daos (r:1 w:0)
        fn enact_proposal() -> Weight {
        (46_310_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(3 as Weight))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
        }
            // Storage: DaoSquare ReserveOf (r:1 w:1)
            // Storage: DaoSquare VotesOf (r:1 w:1)
        fn unlock() -> Weight {
        (44_963_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
        }
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoSquare MinVoteWeightOf (r:0 w:1)
        fn set_min_vote_weight_for_every_call() -> Weight {
        (29_644_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(1 as Weight))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
        }
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoSquare MaxPublicProps (r:0 w:1)
        fn set_max_public_props() -> Weight {
        (29_149_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(1 as Weight))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
        }
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoSquare LaunchPeriod (r:0 w:1)
        fn set_launch_period() -> Weight {
        (29_209_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(1 as Weight))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
        }
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoSquare MinimumDeposit (r:0 w:1)
        fn set_minimum_deposit() -> Weight {
        (29_521_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(1 as Weight))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
        }
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoSquare VotingPeriod (r:0 w:1)
        fn set_voting_period() -> Weight {
        (29_162_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(1 as Weight))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
        }
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoSquare ReservePeriod (r:0 w:1)
        fn set_rerserve_period() -> Weight {
        (29_218_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(1 as Weight))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
        }
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoSquare EnactmentPeriod (r:0 w:1)
        fn set_enactment_period() -> Weight {
        (29_252_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(1 as Weight))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
        }
    }

    // For backwards compatibility and tests
    impl WeightInfo for () {
            // Storage: System Account (r:1 w:1)
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoSquare MinimumDeposit (r:1 w:0)
            // Storage: DaoSquare PublicPropCount (r:1 w:1)
            // Storage: DaoSquare PublicProps (r:1 w:1)
            // Storage: DaoSquare MaxPublicProps (r:1 w:0)
            // Storage: DaoSquare DepositOf (r:0 w:1)
        fn propose() -> Weight {
        (76_544_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(6 as Weight))
            .saturating_add(RocksDbWeight::get().writes(4 as Weight))
        }
            // Storage: DaoSquare DepositOf (r:1 w:1)
            // Storage: System Account (r:1 w:1)
            // Storage: DaoSquare ReservePeriod (r:1 w:0)
            // Storage: DaoSquare ReserveOf (r:1 w:1)
        fn second() -> Weight {
        (54_657_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes(3 as Weight))
        }
            // Storage: DaoSquare LaunchTag (r:1 w:0)
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoSquare LaunchPeriod (r:1 w:0)
            // Storage: DaoSquare PublicProps (r:1 w:1)
            // Storage: DaoSquare DepositOf (r:1 w:1)
            // Storage: DaoSquare VotingPeriod (r:1 w:0)
            // Storage: DaoSquare EnactmentPeriod (r:1 w:0)
            // Storage: DaoSquare ReferendumCount (r:1 w:1)
            // Storage: DaoSquare ReferendumInfoOf (r:0 w:1)
        fn open_table() -> Weight {
        (60_214_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(8 as Weight))
            .saturating_add(RocksDbWeight::get().writes(4 as Weight))
        }
            // Storage: DaoSquare ReferendumInfoOf (r:1 w:1)
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoSquare VotesOf (r:1 w:1)
        fn vote_for_referendum() -> Weight {
        (42_628_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(3 as Weight))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
        }
            // Storage: DaoSquare ReferendumInfoOf (r:1 w:1)
            // Storage: DaoSquare VotesOf (r:1 w:1)
        fn cancel_vote() -> Weight {
        (40_795_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
        }
            // Storage: DaoSquare ReferendumInfoOf (r:1 w:1)
            // Storage: DaoSquare MinVoteWeightOf (r:1 w:0)
            // Storage: CreateDao Daos (r:1 w:0)
        fn enact_proposal() -> Weight {
        (46_310_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(3 as Weight))
            .saturating_add(RocksDbWeight::get().writes(1 as Weight))
        }
            // Storage: DaoSquare ReserveOf (r:1 w:1)
            // Storage: DaoSquare VotesOf (r:1 w:1)
        fn unlock() -> Weight {
        (44_963_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
        }
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoSquare MinVoteWeightOf (r:0 w:1)
        fn set_min_vote_weight_for_every_call() -> Weight {
        (29_644_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(1 as Weight))
            .saturating_add(RocksDbWeight::get().writes(1 as Weight))
        }
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoSquare MaxPublicProps (r:0 w:1)
        fn set_max_public_props() -> Weight {
        (29_149_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(1 as Weight))
            .saturating_add(RocksDbWeight::get().writes(1 as Weight))
        }
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoSquare LaunchPeriod (r:0 w:1)
        fn set_launch_period() -> Weight {
        (29_209_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(1 as Weight))
            .saturating_add(RocksDbWeight::get().writes(1 as Weight))
        }
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoSquare MinimumDeposit (r:0 w:1)
        fn set_minimum_deposit() -> Weight {
        (29_521_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(1 as Weight))
            .saturating_add(RocksDbWeight::get().writes(1 as Weight))
        }
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoSquare VotingPeriod (r:0 w:1)
        fn set_voting_period() -> Weight {
        (29_162_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(1 as Weight))
            .saturating_add(RocksDbWeight::get().writes(1 as Weight))
        }
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoSquare ReservePeriod (r:0 w:1)
        fn set_rerserve_period() -> Weight {
        (29_218_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(1 as Weight))
            .saturating_add(RocksDbWeight::get().writes(1 as Weight))
        }
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoSquare EnactmentPeriod (r:0 w:1)
        fn set_enactment_period() -> Weight {
        (29_252_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(1 as Weight))
            .saturating_add(RocksDbWeight::get().writes(1 as Weight))
        }
    }