//! Autogenerated weights for daos_emergency
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-11-27, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("local"), DB CACHE: 1024

// Executed Command:
    // target/release/tico
    // benchmark
    // pallet
    // --execution=wasm
    // --chain
    // local
    // --wasm-execution=compiled
    // --pallet=daos_emergency
    // --extrinsic=*
    // --steps=50
    // --repeat=20
    // --template=./.maintain/daos-weight-template.hbs
    // --output
    // ./pallets/daos/emergency/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for daos_emergency.
pub trait WeightInfo {
    fn set_members() -> Weight;
    fn set_pledge() -> Weight;
    fn external_track() -> Weight;
    fn internal_track() -> Weight;
    fn reject() -> Weight;
    fn enact_proposal() -> Weight;
}

/// Weights for daos_emergency using the Substrate node and recommended hardware.
pub struct DaosWeight<T>(PhantomData<T>);
        impl<T: frame_system::Config> WeightInfo for DaosWeight<T> {
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoEmergency Members (r:0 w:1)
        fn set_members() -> Weight {
            Weight::from_all(2000_0000)
        }
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoEmergency PledgeOf (r:0 w:1)
        fn set_pledge() -> Weight {
            Weight::from_all(2000_0000)
        }
            // Storage: DaoEmergency HashesOf (r:1 w:1)
            // Storage: DaoEmergency ProposalOf (r:0 w:1)
        fn external_track() -> Weight {
            Weight::from_all(2000_0000)
        }
            // Storage: System Account (r:1 w:1)
            // Storage: DaoEmergency Members (r:1 w:0)
            // Storage: DaoEmergency HashesOf (r:1 w:1)
            // Storage: DaoEmergency PledgeOf (r:1 w:0)
            // Storage: DaoEmergency ProposalOf (r:0 w:1)
        fn internal_track() -> Weight {
            Weight::from_all(2000_0000)
        }
            // Storage: System Account (r:2 w:2)
            // Storage: Currencies UsersNumber (r:1 w:1)
            // Storage: DaoEmergency HashesOf (r:1 w:1)
            // Storage: DaoEmergency ProposalOf (r:1 w:1)
        fn reject() -> Weight {
            Weight::from_all(2000_0000)
        }
            // Storage: System Account (r:2 w:2)
            // Storage: Currencies UsersNumber (r:1 w:1)
            // Storage: DaoEmergency HashesOf (r:1 w:1)
            // Storage: DaoEmergency ProposalOf (r:1 w:1)
            // Storage: CreateDao Daos (r:1 w:0)
        fn enact_proposal() -> Weight {
            Weight::from_all(2000_0000)
        }
    }

    // For backwards compatibility and tests
    impl WeightInfo for () {
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoEmergency Members (r:0 w:1)
        fn set_members() -> Weight {
            Weight::from_all(2000_0000)
        }
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoEmergency PledgeOf (r:0 w:1)
        fn set_pledge() -> Weight {
            Weight::from_all(2000_0000)
        }
            // Storage: DaoEmergency HashesOf (r:1 w:1)
            // Storage: DaoEmergency ProposalOf (r:0 w:1)
        fn external_track() -> Weight {
            Weight::from_all(2000_0000)
        }
            // Storage: System Account (r:1 w:1)
            // Storage: DaoEmergency Members (r:1 w:0)
            // Storage: DaoEmergency HashesOf (r:1 w:1)
            // Storage: DaoEmergency PledgeOf (r:1 w:0)
            // Storage: DaoEmergency ProposalOf (r:0 w:1)
        fn internal_track() -> Weight {
            Weight::from_all(2000_0000)
        }
            // Storage: System Account (r:2 w:2)
            // Storage: Currencies UsersNumber (r:1 w:1)
            // Storage: DaoEmergency HashesOf (r:1 w:1)
            // Storage: DaoEmergency ProposalOf (r:1 w:1)
        fn reject() -> Weight {
            Weight::from_all(2000_0000)
        }
            // Storage: System Account (r:2 w:2)
            // Storage: Currencies UsersNumber (r:1 w:1)
            // Storage: DaoEmergency HashesOf (r:1 w:1)
            // Storage: DaoEmergency ProposalOf (r:1 w:1)
            // Storage: CreateDao Daos (r:1 w:0)
        fn enact_proposal() -> Weight {
            Weight::from_all(2000_0000)
        }
    }