//! Autogenerated weights for daos_doas
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-10-12, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: Some("local"), DB CACHE: 1024

// Executed Command:
    // ./target/release/tico
    // benchmark
    // pallet
    // --chain
    // local
    // --steps=50
    // --repeat=20
    // --pallet=daos-doas
    // --extrinsic=*
    // --template=./.maintain/pallet-weight-template.hbs
    // --output
    // ./pallets/daos/doas/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for daos_doas.
pub trait WeightInfo {
    fn do_as_agency() -> Weight;
}

/// Weights for daos_doas using the Substrate node and recommended hardware.
pub struct DicoWeight<T>(PhantomData<T>);
        impl<T: frame_system::Config> WeightInfo for DicoWeight<T> {
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoCollective EnsureOrigins (r:1 w:0)
        fn do_as_agency() -> Weight {
            Weight::from_ref_time(20_0000_0000)
        }
    }

    // For backwards compatibility and tests
    impl WeightInfo for () {
            // Storage: CreateDao Daos (r:1 w:0)
            // Storage: DaoCollective EnsureOrigins (r:1 w:0)
        fn do_as_agency() -> Weight {
                Weight::from_ref_time(20_0000_0000)
        }
    }